#!/usr/bin/expect
 
# Set variables
set user [lrange $argv 0 0]
set pass [lrange $argv 1 1]
set host [lrange $argv 2 2]
set script [lrange $argv 3 3]
set extra [lrange $argv 4 4]
#set timeout -1
 
# Connect using ssh command
spawn ssh -o StrictHostKeyChecking=no $user@$host $script
match_max 100000

#expect "*Are you sure you want to continue connecting*"
#send   "yes\r"

expect  "*password: $"
send    "$pass\n"
 
#sleep 2
#expect eof
interact